class CustomError extends Error {
  constructor(args) {
    super(args);
    this.message = "Custom error";
  }
  throwGenericError() {
    throw new Error("Generic error");
  }
  throwCustomError() {
    throw new CustomError().message;
  }
}

const newError = new CustomError();

//generic error
console.log("Force generic error");
try {
  console.log("Generic error try block");
  newError.throwGenericError();
} catch {
  console.log("Generic error catch block");
  console.log(newError.throwGenericError());
} finally {
  console.log("Generic error finally block");
}

//custom error
console.log("Force custom error");
try {
  console.log("Custom error try block");
} catch {
  console.log("Custom error catch block");
  console.log(newError.throwCustomError());
} finally {
  console.log("Custom error finally block");
}
